# DPTU: Dynamic Programming Tutor
# 
#  (C) Johanna & Richard Blumenthal, All rights reserved
# 
#  Unauthorized use, duplication or distribution without the authors'
#  permission is strictly prohibited.
# 
#  Unless required by applicable law or agreed to in writing, this
#  software is distributed on an "AS IS" basis without warranties
#  or conditions of any kind, either expressed or implied.


mode.seeOne=See One
mode.doOne=Do One
mode.teachOne=Teach One
mode.teachOne.tooltip=Start a "teach one" session

about=About...

action.signIn.name=Sign In
action.signIn.tooltip=Sign-in to the tutor
action.createAccount.name=Create Account
action.createAccount.tooltip=Create a new user

auth.error.invalidPassword=Authentication Error: Invalid Password!
auth.error.unknownUser=Authentication Error: Unknown User ID!

account.create.success=Student user account successfully created\n\nPress okay and we'll return you to the sign-in screen\n\nThen, please sign-in to the tutor using this account.
account.create.error.duplicateUser=User id already exists: {0}

dialog.title.information=Information
dialog.title.error=Error

error.unknownTryAgain=Unknown Error Occured, Please try again!
error.unexpectedContactSupport=An unexpected error occurred. Please contact DpTu support

app.title.short=DpTu
app.copyright=(C) 2019-2025 Johanna and Richard Blumenthal. All Rights Reserved

dialog.title.signInError=SignIn Error
dialog.title.warning=Warning
dialog.title.welcome=Welcome

auth.error.invalidPasswordAttempt=Invalid Password attempt {0} of {1}
auth.error.maxAttemptsExceeded=You exceeded the max number of sign in attempts\nPlease contact the DpTu administrator
auth.error.unknownUserDetails={0} is not a known user.\n\nPerhaps, try creating a 'New User' first.

dashboard.welcome=Welcome, {0}!
dashboard.welcome.sessionStarted=Welcome, {0}! Your session has successfully started.
dashboard.button.settings=Settings
dashboard.button.logOut=Log Out
dashboard.button.viewStats=View Stats
dashboard.stats.seeOne.title=See One Stats
dashboard.stats.doOne.title=Do One Stats
dashboard.stats.teachOne.title=Teach One Stats

splash.header.department=Regis University Department of Computer and Cyber Sciences
splash.header.newToDptu=New to DpTu?

splash.login.title=Sign in
splash.login.userId=User Id
splash.login.password=Password:

splash.overview.logo=DpTu: Dynamic Programming Tutor
splash.overview.tagline=A See_1, Do_1, Teach_1 Intelligent Tutoring System.
splash.overview.description=DpTu provides individualized tutoring practice focused on understanding Dynamic Programming and the underlying computer science concepts upon which it is based.\n\nPlease sign in or use 'New User' to create a student account.\n\n
splash.overview.loginMsg=To use the tutor, you must sign in.
