package edu.regis.dptu.dao;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
// import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
// import java.util.ArrayList;

import edu.regis.dptu.err.NonRecoverableException;
// import edu.regis.dptu.err.ObjNotFoundException;
// import edu.regis.dptu.model.Course;
// import edu.regis.dptu.model.KnowledgeComponent;
import edu.regis.dptu.model.Student;
// import edu.regis.dptu.model.aol.Assessment;
// import edu.regis.dptu.model.aol.AssessmentLevel;
import edu.regis.dptu.model.aol.StudentModel;
// import edu.regis.dptu.svc.CourseSvc;
// import edu.regis.dptu.svc.ServiceFactory;

/**
 * A Data Access Object implementing {@link StudentModelSvc } behaviors.
 * 
 * @todo temporary
 * Shows how to use the {@link Transactionable} class
 *
 * @author rickb
 * @author benm
 */
public class StudentModelDAO extends Transactionable {

    /**
     * Initialize this DAO via the parent constructor.
     */
    public StudentModelDAO() {
        super();
    }

    public void create(Student student) throws NonRecoverableException {
        final String sql1 = "INSERT INTO StudentModel (UserId, ScaffoldLevel) VALUES (?,?)";

        final String sql2 = "INSERT INTO Assessment (UserId, KnowledgeComponentId, AssessmentLevel, Exposures, Successes, Hints) VALUES (?,?,?,?,?,?)";

        String userId = student.getAccount().getUserId();
        StudentModel studentModel = student.getStudentModel();

        Connection conn = null;
        PreparedStatement stmt1 = null;
        PreparedStatement stmt2 = null;

        try {
            conn = DriverManager.getConnection(URL);
            
            startTransaction(conn);
        
            stmt1 = conn.prepareStatement(sql1);
            
            // stmt1.setString(1, userId);
            // stmt1.setString(2, ScaffoldLevel.EXTREME.toString());
            stmt1.executeUpdate();
            
            stmt2 = conn.prepareStatement(sql2, Statement.RETURN_GENERATED_KEYS);

            // for (Assessment assessment : studentModel.getAssessments().values()) {

            //     stmt2.setString(1, userId);
            //     stmt2.setInt(2, assessment.getOutcome().getId());
            //     stmt2.setString(3, "Not Started");
            //     stmt2.setInt(4, assessment.getExposures());
            //     stmt2.setInt(5, assessment.getSuccessess());
            //     stmt2.setInt(6, assessment.getHints());

            //     stmt2.executeUpdate();

            //     Get the id/key autogenerated by the DB
            //     ResultSet rs = stmt2.getGeneratedKeys();
            //     if (rs.next()) {
            //         assessment.setId(rs.getInt(1));
            //     }
            // }

            commit(conn);
        } catch (SQLException e) {
            if (conn != null) rollback(conn);
            throw new NonRecoverableException("UserDAO-ERR-5" + e.toString(), e);
        } finally {
            close(stmt2);
            close(conn, stmt1);
        }
    }
}
